export const locales = ["pt", "en", "es", "de"] as const;
export type Locale = (typeof locales)[number];

const en = {
  "brand.full": "System Operations Navigator", "common.demo": "Demo environment", "common.demoData": "Demo data", "common.localOnly": "Local demonstration only.", "common.backOverview": "Back to Overview",
  "nav.overview": "Overview", "nav.assistant": "Assistant", "nav.knowledge": "Knowledge", "nav.equipment": "Equipment", "nav.activity": "Activity", "nav.report": "Report Issue", "nav.supervisor": "Supervisor", "nav.primary": "Primary navigation", "nav.mobile": "Mobile navigation",
  "topbar.context": "Plant operations · Demo workspace", "topbar.language": "Language", "topbar.collapse": "Collapse sidebar", "topbar.expand": "Expand sidebar", "topbar.menu": "Open navigation", "topbar.close": "Close navigation", "topbar.notifications": "Notifications", "profile.name": "Operator 04", "profile.role": "Operations",
  "overview.eyebrow": "Operator workspace", "overview.title": "Good morning.", "overview.description": "What do you need help with?", "overview.actions": "Operational actions",
  "action.ask": "Ask SON", "action.askDesc": "Get operational guidance", "action.troubleshoot": "Troubleshoot", "action.troubleshootDesc": "Investigate an issue step by step", "action.procedures": "Procedures", "action.proceduresDesc": "Browse controlled documents", "action.equipment": "Equipment", "action.equipmentDesc": "View asset information", "action.report": "Report Issue", "action.reportDesc": "Create a local demo report",
  "recent.title": "Recent activity", "recent.viewAll": "View all", "recent.asset": "Asset", "recent.activity": "Activity", "recent.updated": "Updated", "recent.status": "Status", "recent.e42": "Error E42 investigation", "recent.startup": "Startup procedure", "recent.pressure": "Pressure inspection", "time.8min": "8 min ago", "time.42min": "42 min ago", "time.yesterday": "Yesterday", "status.progress": "In progress", "status.completed": "Completed", "status.escalated": "Escalated",
  "assistant.eyebrow": "Operational Assistant", "assistant.title": "Ask SON", "assistant.modes": "Explain · Guide · Verify", "assistant.connected": "AI connected", "assistant.safety": "SON provides information and guidance only. Safety-critical or authorized actions must be escalated to the responsible human role.", "assistant.welcome": "Describe the equipment, alarm, observation or procedure you need help with. I’ll keep guidance focused and flag when an authorized person must take over.", "assistant.promptFault": "Line 3 stopped and is showing error E42.", "assistant.promptExplain": "Explain what a pressure interlock does.", "assistant.promptVerify": "I measured 6.2 bar at Pump P-204. Help me verify the observation.", "assistant.sources": "Sources", "assistant.analyzing": "SON is analyzing", "assistant.error": "SON is temporarily unavailable. Try again.", "assistant.retry": "Retry", "assistant.placeholder": "Describe an operational issue, observation or procedure…", "assistant.send": "Send message", "assistant.noRetrieval": "No live equipment or document retrieval is connected in this demonstration.", "assistant.conversation": "Operational conversation",
  "knowledge.eyebrow": "Knowledge", "knowledge.title": "Operational knowledge base", "knowledge.description": "A RAG-ready interface for controlled industrial documents.", "knowledge.noticeTitle": "Demonstration content only.", "knowledge.notice": "No document retrieval pipeline is connected. SON will not claim to have accessed these files.", "knowledge.manuals": "Manuals", "knowledge.manualsDesc": "Equipment operation and reference", "knowledge.sops": "SOPs", "knowledge.sopsDesc": "Standard operating procedures", "knowledge.instructions": "Work Instructions", "knowledge.instructionsDesc": "Task-level instructions", "knowledge.safety": "Safety Procedures", "knowledge.safetyDesc": "Controlled safety guidance", "knowledge.datasheets": "Technical Datasheets", "knowledge.datasheetsDesc": "Asset specifications", "knowledge.records": "Maintenance Records", "knowledge.recordsDesc": "Service history and notes", "knowledge.demoFiles": "{count} demo files", "knowledge.demoRecords": "{count} demo records", "knowledge.static": "Static examples", "knowledge.recent": "Recently accessed", "knowledge.docConveyor": "Conveyor L3 restart and inspection", "knowledge.docManual": "X200 conveyor technical manual", "knowledge.docBelt": "Scheduled belt tension inspection", "knowledge.revision": "SOP · Revision 4", "knowledge.pages": "Manual · 112 pages", "knowledge.maintenanceProcedure": "Maintenance procedure",
  "equipment.eyebrow": "Equipment", "equipment.title": "Asset directory", "equipment.description": "Review local demonstration assets and operational context.", "equipment.search": "Search equipment or asset ID", "equipment.material": "Material handling", "equipment.packaging": "Packaging", "equipment.utilities": "Utilities", "equipment.processing": "Processing", "equipment.attention": "Attention", "equipment.operational": "Operational", "equipment.inspection": "Inspection due", "equipment.view": "View demo details",
  "activity.eyebrow": "Activity", "activity.title": "Operational history", "activity.description": "A local timeline of demonstration sessions and events.", "activity.troubleshooting": "Troubleshooting started", "activity.troubleshootingDetail": "Operator 04 · Conveyor L3 · Error E42", "activity.procedure": "Procedure completed", "activity.procedureDetail": "Operator 02 · Packaging Line · SOP-PK-002", "activity.escalated": "Observation escalated", "activity.escalatedDetail": "Pump P-204 · Pressure outside expected range", "activity.document": "Document accessed", "activity.investigation": "Investigation", "activity.knowledge": "Knowledge",
  "supervisor.eyebrow": "Supervisor Area", "supervisor.title": "Operations overview", "supervisor.description": "Local demonstration data for team and asset visibility.", "supervisor.operatorWorkspace": "Operator Workspace", "supervisor.activeSessions": "Active Sessions", "supervisor.operators": "Operators", "supervisor.openAlerts": "Open Alerts", "supervisor.live": "Live operations", "supervisor.session1": "Operator 04 is troubleshooting Conveyor L3", "supervisor.session1Meta": "Error E42 · Started 8 minutes ago", "supervisor.session2": "Operator 02 is reviewing a startup procedure", "supervisor.reviewing": "Reviewing", "supervisor.escalations": "Escalations", "supervisor.attention": "Needs attention", "supervisor.pump": "Pressure observation requires authorized review.", "supervisor.conveyor": "Repeated E42 alarm in demo session.", "supervisor.procedures": "Procedures accessed", "supervisor.documentActivity": "Document activity", "supervisor.views6": "6 views today", "supervisor.views3": "3 views today", "supervisor.views2": "2 views today", "supervisor.history": "Activity history", "supervisor.latest": "Latest events", "supervisor.knowledgeAccessed": "Knowledge accessed",
  "report.eyebrow": "Report issue", "report.title": "Record an operational observation", "report.description": "Capture a local demonstration report for supervisor review.", "report.asset": "Equipment or area", "report.assetPlaceholder": "e.g. Conveyor L3", "report.category": "Issue category", "report.select": "Select a category", "report.alarm": "Alarm or fault", "report.unexpected": "Unexpected observation", "report.procedure": "Procedure question", "report.safety": "Safety concern", "report.observation": "Observation", "report.observationPlaceholder": "Describe what you observed. Do not perform an unsafe intervention.", "report.notice": "This form does not notify a real supervisor or create a production ticket.", "report.submit": "Record demo report", "report.successTitle": "Demo report recorded", "report.successDescription": "This confirmation is local only. No production workflow or external system was contacted.", "report.ready": "Report ready for review", "report.readyDescription": "An authorized supervisor would review and route this observation in a connected deployment.", "report.return": "Return to Overview",
} as const;

export type TranslationKey = keyof typeof en;
type Dictionary = Record<TranslationKey, string>;

const pt: Dictionary = { ...en,
  "common.demo": "Ambiente de demonstração", "common.demoData": "Dados de demonstração", "common.localOnly": "Apenas demonstração local.", "common.backOverview": "Voltar à Visão geral",
  "nav.overview": "Visão geral", "nav.assistant": "Assistente", "nav.knowledge": "Conhecimento", "nav.equipment": "Equipamentos", "nav.activity": "Atividade", "nav.report": "Reportar problema", "nav.supervisor": "Supervisor", "nav.primary": "Navegação principal", "nav.mobile": "Navegação móvel",
  "topbar.context": "Operações da fábrica · Espaço de demonstração", "topbar.language": "Idioma", "topbar.collapse": "Recolher barra lateral", "topbar.expand": "Expandir barra lateral", "topbar.menu": "Abrir navegação", "topbar.close": "Fechar navegação", "topbar.notifications": "Notificações", "profile.role": "Operações",
  "overview.eyebrow": "Espaço do operador", "overview.title": "Bom dia.", "overview.description": "Em que precisa de ajuda?", "overview.actions": "Ações operacionais",
  "action.ask": "Perguntar ao SON", "action.askDesc": "Obtenha orientação operacional", "action.troubleshoot": "Diagnosticar", "action.troubleshootDesc": "Investigue um problema passo a passo", "action.procedures": "Procedimentos", "action.proceduresDesc": "Consulte documentos controlados", "action.equipment": "Equipamentos", "action.equipmentDesc": "Veja informações dos ativos", "action.report": "Reportar problema", "action.reportDesc": "Crie um relatório local de demonstração",
  "recent.title": "Atividade recente", "recent.viewAll": "Ver tudo", "recent.asset": "Ativo", "recent.activity": "Atividade", "recent.updated": "Atualizado", "recent.status": "Estado", "recent.e42": "Investigação do erro E42", "recent.startup": "Procedimento de arranque", "recent.pressure": "Inspeção de pressão", "time.8min": "Há 8 min", "time.42min": "Há 42 min", "time.yesterday": "Ontem", "status.progress": "Em curso", "status.completed": "Concluído", "status.escalated": "Escalado",
  "assistant.eyebrow": "Assistente Operacional", "assistant.title": "Perguntar ao SON", "assistant.modes": "Explicar · Orientar · Verificar", "assistant.connected": "IA ligada", "assistant.safety": "O SON fornece apenas informação e orientação. Ações críticas de segurança ou sujeitas a autorização devem ser escaladas para o responsável humano.", "assistant.welcome": "Descreva o equipamento, alarme, observação ou procedimento. Manterei a orientação objetiva e indicarei quando uma pessoa autorizada deve intervir.", "assistant.promptFault": "A Linha 3 parou e apresenta o erro E42.", "assistant.promptExplain": "Explique o que faz um interbloqueio de pressão.", "assistant.promptVerify": "Medi 6,2 bar na Bomba P-204. Ajude-me a verificar a observação.", "assistant.sources": "Fontes", "assistant.analyzing": "O SON está a analisar", "assistant.error": "O SON está temporariamente indisponível. Tente novamente.", "assistant.retry": "Tentar novamente", "assistant.placeholder": "Descreva um problema, observação ou procedimento operacional…", "assistant.send": "Enviar mensagem", "assistant.noRetrieval": "Nenhum equipamento em tempo real ou sistema de pesquisa documental está ligado nesta demonstração.", "assistant.conversation": "Conversa operacional",
  "knowledge.title": "Base de conhecimento operacional", "knowledge.description": "Uma interface preparada para RAG e documentos industriais controlados.", "knowledge.noticeTitle": "Apenas conteúdo de demonstração.", "knowledge.notice": "Não existe um pipeline de pesquisa documental ligado. O SON não afirmará ter acedido a estes ficheiros.", "knowledge.manuals": "Manuais", "knowledge.manualsDesc": "Operação e referência de equipamentos", "knowledge.sopsDesc": "Procedimentos operacionais normalizados", "knowledge.instructions": "Instruções de trabalho", "knowledge.instructionsDesc": "Instruções ao nível da tarefa", "knowledge.safety": "Procedimentos de segurança", "knowledge.safetyDesc": "Orientação de segurança controlada", "knowledge.datasheets": "Fichas técnicas", "knowledge.datasheetsDesc": "Especificações dos ativos", "knowledge.records": "Registos de manutenção", "knowledge.recordsDesc": "Histórico e notas de serviço", "knowledge.demoFiles": "{count} ficheiros demo", "knowledge.demoRecords": "{count} registos demo", "knowledge.static": "Exemplos estáticos", "knowledge.recent": "Acedidos recentemente", "knowledge.docConveyor": "Reinício e inspeção do Transportador L3", "knowledge.docManual": "Manual técnico do transportador X200", "knowledge.docBelt": "Inspeção programada da tensão da correia", "knowledge.revision": "SOP · Revisão 4", "knowledge.pages": "Manual · 112 páginas", "knowledge.maintenanceProcedure": "Procedimento de manutenção",
  "equipment.eyebrow": "Equipamentos", "equipment.title": "Diretório de ativos", "equipment.description": "Consulte ativos locais de demonstração e contexto operacional.", "equipment.search": "Pesquisar equipamento ou ID do ativo", "equipment.material": "Movimentação de materiais", "equipment.packaging": "Embalagem", "equipment.utilities": "Utilidades", "equipment.processing": "Processamento", "equipment.attention": "Atenção", "equipment.operational": "Operacional", "equipment.inspection": "Inspeção pendente", "equipment.view": "Ver detalhes demo",
  "activity.title": "Histórico operacional", "activity.description": "Linha temporal local de sessões e eventos de demonstração.", "activity.troubleshooting": "Diagnóstico iniciado", "activity.procedure": "Procedimento concluído", "activity.escalated": "Observação escalada", "activity.document": "Documento consultado", "activity.investigation": "Investigação", "activity.knowledge": "Conhecimento", "activity.escalatedDetail": "Bomba P-204 · Pressão fora do intervalo esperado",
  "supervisor.title": "Visão geral das operações", "supervisor.description": "Dados locais de demonstração para visibilidade da equipa e dos ativos.", "supervisor.operatorWorkspace": "Espaço do operador", "supervisor.activeSessions": "Sessões ativas", "supervisor.operators": "Operadores", "supervisor.openAlerts": "Alertas abertos", "supervisor.live": "Operações em direto", "supervisor.session1": "Operador 04 está a diagnosticar o Transportador L3", "supervisor.session1Meta": "Erro E42 · Iniciado há 8 minutos", "supervisor.session2": "Operador 02 está a rever um procedimento de arranque", "supervisor.reviewing": "Em revisão", "supervisor.escalations": "Escalamentos", "supervisor.attention": "Requer atenção", "supervisor.pump": "A observação de pressão requer revisão autorizada.", "supervisor.conveyor": "Alarme E42 repetido na sessão demo.", "supervisor.procedures": "Procedimentos consultados", "supervisor.documentActivity": "Atividade documental", "supervisor.views6": "6 visualizações hoje", "supervisor.views3": "3 visualizações hoje", "supervisor.views2": "2 visualizações hoje", "supervisor.history": "Histórico de atividade", "supervisor.latest": "Eventos recentes", "supervisor.knowledgeAccessed": "Conhecimento consultado",
  "report.title": "Registar uma observação operacional", "report.description": "Crie um relatório local de demonstração para revisão do supervisor.", "report.asset": "Equipamento ou área", "report.assetPlaceholder": "ex.: Transportador L3", "report.category": "Categoria do problema", "report.select": "Selecione uma categoria", "report.alarm": "Alarme ou avaria", "report.unexpected": "Observação inesperada", "report.procedure": "Questão de procedimento", "report.safety": "Questão de segurança", "report.observation": "Observação", "report.observationPlaceholder": "Descreva o que observou. Não efetue uma intervenção insegura.", "report.notice": "Este formulário não notifica um supervisor real nem cria um ticket de produção.", "report.submit": "Registar relatório demo", "report.successTitle": "Relatório demo registado", "report.successDescription": "Esta confirmação é apenas local. Nenhum fluxo de produção ou sistema externo foi contactado.", "report.ready": "Relatório pronto para revisão", "report.readyDescription": "Num ambiente ligado, um supervisor autorizado analisaria e encaminharia esta observação.", "report.return": "Voltar à Visão geral",
};

const es: Dictionary = { ...en,
  "common.demo": "Entorno de demostración", "common.demoData": "Datos de demostración", "common.localOnly": "Solo demostración local.", "common.backOverview": "Volver al Resumen",
  "nav.overview": "Resumen", "nav.assistant": "Asistente", "nav.knowledge": "Conocimiento", "nav.equipment": "Equipos", "nav.activity": "Actividad", "nav.report": "Informar problema", "nav.supervisor": "Supervisor", "nav.primary": "Navegación principal", "nav.mobile": "Navegación móvil",
  "topbar.context": "Operaciones de planta · Espacio de demostración", "topbar.language": "Idioma", "topbar.collapse": "Contraer barra lateral", "topbar.expand": "Expandir barra lateral", "topbar.menu": "Abrir navegación", "topbar.close": "Cerrar navegación", "topbar.notifications": "Notificaciones", "profile.role": "Operaciones",
  "overview.eyebrow": "Espacio del operador", "overview.title": "Buenos días.", "overview.description": "¿En qué necesitas ayuda?", "overview.actions": "Acciones operativas",
  "action.ask": "Preguntar a SON", "action.askDesc": "Obtén orientación operativa", "action.troubleshoot": "Diagnosticar", "action.troubleshootDesc": "Investiga un problema paso a paso", "action.procedures": "Procedimientos", "action.proceduresDesc": "Consulta documentos controlados", "action.equipment": "Equipos", "action.equipmentDesc": "Consulta información de activos", "action.report": "Informar problema", "action.reportDesc": "Crea un informe local de demostración",
  "recent.title": "Actividad reciente", "recent.viewAll": "Ver todo", "recent.asset": "Activo", "recent.activity": "Actividad", "recent.updated": "Actualizado", "recent.status": "Estado", "recent.e42": "Investigación del error E42", "recent.startup": "Procedimiento de arranque", "recent.pressure": "Inspección de presión", "time.8min": "Hace 8 min", "time.42min": "Hace 42 min", "time.yesterday": "Ayer", "status.progress": "En curso", "status.completed": "Completado", "status.escalated": "Escalado",
  "assistant.eyebrow": "Asistente Operacional", "assistant.title": "Preguntar a SON", "assistant.modes": "Explicar · Guiar · Verificar", "assistant.connected": "IA conectada", "assistant.safety": "SON solo proporciona información y orientación. Las acciones críticas de seguridad o sujetas a autorización deben escalarse al responsable humano.", "assistant.welcome": "Describe el equipo, alarma, observación o procedimiento. Mantendré la orientación enfocada e indicaré cuándo debe intervenir una persona autorizada.", "assistant.promptFault": "La Línea 3 se detuvo y muestra el error E42.", "assistant.promptExplain": "Explica qué hace un interbloqueo de presión.", "assistant.promptVerify": "Medí 6,2 bar en la Bomba P-204. Ayúdame a verificar la observación.", "assistant.sources": "Fuentes", "assistant.analyzing": "SON está analizando", "assistant.error": "SON no está disponible temporalmente. Inténtalo de nuevo.", "assistant.retry": "Reintentar", "assistant.placeholder": "Describe un problema, observación o procedimiento operativo…", "assistant.send": "Enviar mensaje", "assistant.noRetrieval": "No hay equipos en vivo ni recuperación documental conectados en esta demostración.", "assistant.conversation": "Conversación operativa",
  "knowledge.title": "Base de conocimiento operacional", "knowledge.description": "Una interfaz preparada para RAG y documentos industriales controlados.", "knowledge.noticeTitle": "Solo contenido de demostración.", "knowledge.notice": "No hay un pipeline de recuperación documental conectado. SON no afirmará haber accedido a estos archivos.", "knowledge.manuals": "Manuales", "knowledge.manualsDesc": "Operación y referencia de equipos", "knowledge.sopsDesc": "Procedimientos operativos estándar", "knowledge.instructions": "Instrucciones de trabajo", "knowledge.instructionsDesc": "Instrucciones a nivel de tarea", "knowledge.safety": "Procedimientos de seguridad", "knowledge.safetyDesc": "Orientación de seguridad controlada", "knowledge.datasheets": "Fichas técnicas", "knowledge.datasheetsDesc": "Especificaciones de activos", "knowledge.records": "Registros de mantenimiento", "knowledge.recordsDesc": "Historial y notas de servicio", "knowledge.demoFiles": "{count} archivos demo", "knowledge.demoRecords": "{count} registros demo", "knowledge.static": "Ejemplos estáticos", "knowledge.recent": "Accedidos recientemente", "knowledge.docConveyor": "Reinicio e inspección del Transportador L3", "knowledge.docManual": "Manual técnico del transportador X200", "knowledge.docBelt": "Inspección programada de tensión de correa", "knowledge.revision": "SOP · Revisión 4", "knowledge.pages": "Manual · 112 páginas", "knowledge.maintenanceProcedure": "Procedimiento de mantenimiento",
  "equipment.eyebrow": "Equipos", "equipment.title": "Directorio de activos", "equipment.description": "Consulta activos locales de demostración y contexto operativo.", "equipment.search": "Buscar equipo o ID de activo", "equipment.material": "Manipulación de materiales", "equipment.packaging": "Embalaje", "equipment.utilities": "Servicios", "equipment.processing": "Procesamiento", "equipment.attention": "Atención", "equipment.operational": "Operativo", "equipment.inspection": "Inspección pendiente", "equipment.view": "Ver detalles demo",
  "activity.title": "Historial operativo", "activity.description": "Cronología local de sesiones y eventos de demostración.", "activity.troubleshooting": "Diagnóstico iniciado", "activity.procedure": "Procedimiento completado", "activity.escalated": "Observación escalada", "activity.document": "Documento consultado", "activity.investigation": "Investigación", "activity.knowledge": "Conocimiento", "activity.escalatedDetail": "Bomba P-204 · Presión fuera del rango esperado",
  "supervisor.title": "Resumen de operaciones", "supervisor.description": "Datos locales de demostración para visibilidad de equipo y activos.", "supervisor.operatorWorkspace": "Espacio del operador", "supervisor.activeSessions": "Sesiones activas", "supervisor.operators": "Operadores", "supervisor.openAlerts": "Alertas abiertas", "supervisor.live": "Operaciones en vivo", "supervisor.session1": "Operador 04 está diagnosticando el Transportador L3", "supervisor.session1Meta": "Error E42 · Iniciado hace 8 minutos", "supervisor.session2": "Operador 02 está revisando un procedimiento de arranque", "supervisor.reviewing": "En revisión", "supervisor.escalations": "Escalamientos", "supervisor.attention": "Requiere atención", "supervisor.pump": "La observación de presión requiere revisión autorizada.", "supervisor.conveyor": "Alarma E42 repetida en la sesión demo.", "supervisor.procedures": "Procedimientos consultados", "supervisor.documentActivity": "Actividad documental", "supervisor.views6": "6 vistas hoy", "supervisor.views3": "3 vistas hoy", "supervisor.views2": "2 vistas hoy", "supervisor.history": "Historial de actividad", "supervisor.latest": "Últimos eventos", "supervisor.knowledgeAccessed": "Conocimiento consultado",
  "report.title": "Registrar una observación operativa", "report.description": "Crea un informe local de demostración para revisión del supervisor.", "report.asset": "Equipo o área", "report.assetPlaceholder": "p. ej. Transportador L3", "report.category": "Categoría del problema", "report.select": "Selecciona una categoría", "report.alarm": "Alarma o fallo", "report.unexpected": "Observación inesperada", "report.procedure": "Pregunta sobre procedimiento", "report.safety": "Problema de seguridad", "report.observation": "Observación", "report.observationPlaceholder": "Describe lo observado. No realices una intervención insegura.", "report.notice": "Este formulario no notifica a un supervisor real ni crea un ticket de producción.", "report.submit": "Registrar informe demo", "report.successTitle": "Informe demo registrado", "report.successDescription": "Esta confirmación es solo local. No se contactó ningún flujo de producción ni sistema externo.", "report.ready": "Informe listo para revisión", "report.readyDescription": "En un entorno conectado, un supervisor autorizado revisaría y derivaría esta observación.", "report.return": "Volver al Resumen",
};

const de: Dictionary = { ...en,
  "common.demo": "Demo-Umgebung", "common.demoData": "Demodaten", "common.localOnly": "Nur lokale Demonstration.", "common.backOverview": "Zurück zur Übersicht",
  "nav.overview": "Übersicht", "nav.assistant": "Assistent", "nav.knowledge": "Wissen", "nav.equipment": "Anlagen", "nav.activity": "Aktivität", "nav.report": "Problem melden", "nav.supervisor": "Leitung", "nav.primary": "Hauptnavigation", "nav.mobile": "Mobile Navigation",
  "topbar.context": "Werksbetrieb · Demo-Arbeitsbereich", "topbar.language": "Sprache", "topbar.collapse": "Seitenleiste einklappen", "topbar.expand": "Seitenleiste ausklappen", "topbar.menu": "Navigation öffnen", "topbar.close": "Navigation schließen", "topbar.notifications": "Benachrichtigungen", "profile.role": "Betrieb",
  "overview.eyebrow": "Operator-Arbeitsbereich", "overview.title": "Guten Morgen.", "overview.description": "Wobei benötigen Sie Hilfe?", "overview.actions": "Betriebsaktionen",
  "action.ask": "SON fragen", "action.askDesc": "Betriebliche Unterstützung erhalten", "action.troubleshoot": "Fehleranalyse", "action.troubleshootDesc": "Ein Problem Schritt für Schritt untersuchen", "action.procedures": "Verfahren", "action.proceduresDesc": "Kontrollierte Dokumente durchsuchen", "action.equipment": "Anlagen", "action.equipmentDesc": "Anlageninformationen anzeigen", "action.report": "Problem melden", "action.reportDesc": "Lokalen Demobericht erstellen",
  "recent.title": "Letzte Aktivitäten", "recent.viewAll": "Alle anzeigen", "recent.asset": "Anlage", "recent.activity": "Aktivität", "recent.updated": "Aktualisiert", "recent.status": "Status", "recent.e42": "Untersuchung Fehler E42", "recent.startup": "Anfahrverfahren", "recent.pressure": "Druckprüfung", "time.8min": "Vor 8 Min.", "time.42min": "Vor 42 Min.", "time.yesterday": "Gestern", "status.progress": "In Bearbeitung", "status.completed": "Abgeschlossen", "status.escalated": "Eskaliert",
  "assistant.eyebrow": "Betriebsassistent", "assistant.title": "SON fragen", "assistant.modes": "Erklären · Anleiten · Prüfen", "assistant.connected": "KI verbunden", "assistant.safety": "SON stellt nur Informationen und Anleitungen bereit. Sicherheitskritische oder genehmigungspflichtige Maßnahmen müssen an die zuständige Person eskaliert werden.", "assistant.welcome": "Beschreiben Sie Anlage, Alarm, Beobachtung oder Verfahren. Ich halte die Anleitung fokussiert und kennzeichne, wann eine autorisierte Person übernehmen muss.", "assistant.promptFault": "Linie 3 ist gestoppt und zeigt Fehler E42.", "assistant.promptExplain": "Erkläre die Funktion einer Druckverriegelung.", "assistant.promptVerify": "Ich habe 6,2 bar an Pumpe P-204 gemessen. Hilf mir, die Beobachtung zu prüfen.", "assistant.sources": "Quellen", "assistant.analyzing": "SON analysiert", "assistant.error": "SON ist vorübergehend nicht verfügbar. Bitte erneut versuchen.", "assistant.retry": "Erneut versuchen", "assistant.placeholder": "Betriebsproblem, Beobachtung oder Verfahren beschreiben…", "assistant.send": "Nachricht senden", "assistant.noRetrieval": "In dieser Demo sind keine Live-Anlagen oder Dokumentenabrufe verbunden.", "assistant.conversation": "Betriebsgespräch",
  "knowledge.title": "Betriebliche Wissensbasis", "knowledge.description": "Eine RAG-bereite Oberfläche für kontrollierte Industriedokumente.", "knowledge.noticeTitle": "Nur Demonstrationsinhalte.", "knowledge.notice": "Keine Dokumentenabfrage ist verbunden. SON behauptet nicht, auf diese Dateien zugegriffen zu haben.", "knowledge.manuals": "Handbücher", "knowledge.manualsDesc": "Anlagenbetrieb und Referenz", "knowledge.sopsDesc": "Standardarbeitsverfahren", "knowledge.instructions": "Arbeitsanweisungen", "knowledge.instructionsDesc": "Aufgabenbezogene Anweisungen", "knowledge.safety": "Sicherheitsverfahren", "knowledge.safetyDesc": "Kontrollierte Sicherheitsanleitung", "knowledge.datasheets": "Technische Datenblätter", "knowledge.datasheetsDesc": "Anlagenspezifikationen", "knowledge.records": "Wartungsunterlagen", "knowledge.recordsDesc": "Servicehistorie und Notizen", "knowledge.demoFiles": "{count} Demo-Dateien", "knowledge.demoRecords": "{count} Demo-Einträge", "knowledge.static": "Statische Beispiele", "knowledge.recent": "Kürzlich aufgerufen", "knowledge.docConveyor": "Neustart und Inspektion Förderer L3", "knowledge.docManual": "Technisches Handbuch Förderer X200", "knowledge.docBelt": "Planmäßige Prüfung der Bandspannung", "knowledge.revision": "SOP · Revision 4", "knowledge.pages": "Handbuch · 112 Seiten", "knowledge.maintenanceProcedure": "Wartungsverfahren",
  "equipment.eyebrow": "Anlagen", "equipment.title": "Anlagenverzeichnis", "equipment.description": "Lokale Demoanlagen und Betriebskontext anzeigen.", "equipment.search": "Anlage oder Anlagen-ID suchen", "equipment.material": "Materialtransport", "equipment.packaging": "Verpackung", "equipment.utilities": "Versorgung", "equipment.processing": "Verarbeitung", "equipment.attention": "Achtung", "equipment.operational": "Betriebsbereit", "equipment.inspection": "Prüfung fällig", "equipment.view": "Demodetails anzeigen",
  "activity.title": "Betriebsverlauf", "activity.description": "Lokale Zeitleiste von Demositzungen und Ereignissen.", "activity.troubleshooting": "Fehleranalyse gestartet", "activity.procedure": "Verfahren abgeschlossen", "activity.escalated": "Beobachtung eskaliert", "activity.document": "Dokument aufgerufen", "activity.investigation": "Untersuchung", "activity.knowledge": "Wissen", "activity.escalatedDetail": "Pumpe P-204 · Druck außerhalb des erwarteten Bereichs",
  "supervisor.title": "Betriebsübersicht", "supervisor.description": "Lokale Demodaten für Team- und Anlagentransparenz.", "supervisor.operatorWorkspace": "Operator-Arbeitsbereich", "supervisor.activeSessions": "Aktive Sitzungen", "supervisor.operators": "Operatoren", "supervisor.openAlerts": "Offene Alarme", "supervisor.live": "Live-Betrieb", "supervisor.session1": "Operator 04 untersucht Förderer L3", "supervisor.session1Meta": "Fehler E42 · Vor 8 Minuten gestartet", "supervisor.session2": "Operator 02 prüft ein Anfahrverfahren", "supervisor.reviewing": "In Prüfung", "supervisor.escalations": "Eskalationen", "supervisor.attention": "Handlungsbedarf", "supervisor.pump": "Die Druckbeobachtung erfordert eine autorisierte Prüfung.", "supervisor.conveyor": "Wiederholter E42-Alarm in der Demositzung.", "supervisor.procedures": "Aufgerufene Verfahren", "supervisor.documentActivity": "Dokumentenaktivität", "supervisor.views6": "6 Aufrufe heute", "supervisor.views3": "3 Aufrufe heute", "supervisor.views2": "2 Aufrufe heute", "supervisor.history": "Aktivitätsverlauf", "supervisor.latest": "Letzte Ereignisse", "supervisor.knowledgeAccessed": "Wissen aufgerufen",
  "report.title": "Betriebliche Beobachtung erfassen", "report.description": "Lokalen Demobericht zur Prüfung durch die Leitung erfassen.", "report.asset": "Anlage oder Bereich", "report.assetPlaceholder": "z. B. Förderer L3", "report.category": "Problemkategorie", "report.select": "Kategorie auswählen", "report.alarm": "Alarm oder Störung", "report.unexpected": "Unerwartete Beobachtung", "report.procedure": "Verfahrensfrage", "report.safety": "Sicherheitsbedenken", "report.observation": "Beobachtung", "report.observationPlaceholder": "Beobachtung beschreiben. Keine unsichere Maßnahme durchführen.", "report.notice": "Dieses Formular informiert keine reale Leitung und erstellt kein Produktionsticket.", "report.submit": "Demobericht erfassen", "report.successTitle": "Demobericht erfasst", "report.successDescription": "Diese Bestätigung ist nur lokal. Kein Produktionsablauf oder externes System wurde kontaktiert.", "report.ready": "Bericht zur Prüfung bereit", "report.readyDescription": "In einer verbundenen Umgebung würde eine autorisierte Leitung diese Beobachtung prüfen und weiterleiten.", "report.return": "Zurück zur Übersicht",
};

export const translations: Record<Locale, Dictionary> = { pt, en, es, de };
export function translate(locale: Locale, key: TranslationKey, variables?: Record<string, string | number>) { let value = translations[locale][key] ?? en[key]; for (const [name, replacement] of Object.entries(variables ?? {})) value = value.replaceAll(`{${name}}`, String(replacement)); return value; }
export function isLocale(value: string | null): value is Locale { return value !== null && locales.includes(value as Locale); }
