create extension if not exists pgcrypto;

create table if not exists public.liio_families (
  id uuid primary key default gen_random_uuid(),
  owner_secret_hash text not null,
  parent_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.liio_children (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.liio_families(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 40),
  age integer not null check (age between 6 and 15),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.liio_preferences (
  family_id uuid primary key references public.liio_families(id) on delete cascade,
  language text not null default 'en' check (language in ('pt','en','es','de')),
  updated_at timestamptz not null default now()
);

create table if not exists public.liio_pairing_codes (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.liio_families(id) on delete cascade,
  code_hash text not null unique,
  expires_at timestamptz not null,
  redeemed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.liio_device_sessions (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.liio_families(id) on delete cascade,
  child_id uuid not null references public.liio_children(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null default (now() + interval '30 days'),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.liio_time_limits (
  child_id uuid primary key references public.liio_children(id) on delete cascade,
  daily_minutes integer not null default 60 check (daily_minutes between 15 and 180),
  quiet_start time not null default '20:00',
  quiet_end time not null default '07:00',
  homework_enabled boolean not null default true,
  voice_enabled boolean not null default true,
  create_world_enabled boolean not null default false,
  paused boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.liio_learning_sessions (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.liio_children(id) on delete cascade,
  device_session_id uuid references public.liio_device_sessions(id) on delete set null,
  mode text not null default 'homework',
  language text not null default 'en' check (language in ('pt','en','es','de')),
  prompt_version text not null,
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

create table if not exists public.liio_activity_events (
  id bigint generated by default as identity primary key,
  child_id uuid not null references public.liio_children(id) on delete cascade,
  learning_session_id uuid references public.liio_learning_sessions(id) on delete set null,
  event_type text not null,
  behavior text,
  duration_ms integer,
  success boolean,
  prompt_version text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.liio_families enable row level security;
alter table public.liio_children enable row level security;
alter table public.liio_preferences enable row level security;
alter table public.liio_pairing_codes enable row level security;
alter table public.liio_device_sessions enable row level security;
alter table public.liio_time_limits enable row level security;
alter table public.liio_learning_sessions enable row level security;
alter table public.liio_activity_events enable row level security;

create or replace function public.liio_hash(value text)
returns text
language sql
immutable
as $$
  select encode(digest(value, 'sha256'), 'hex')
$$;

create or replace function public.liio_owner_matches(
  p_family_id uuid,
  p_owner_secret text
)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.liio_families f
    where f.id = p_family_id
      and f.owner_secret_hash = public.liio_hash(p_owner_secret)
  )
$$;

create or replace function public.liio_create_family(
  p_owner_secret text,
  p_parent_name text,
  p_language text default 'en'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_family_id uuid;
begin
  if char_length(p_owner_secret) < 32 then
    raise exception 'invalid owner secret';
  end if;

  if p_language not in ('pt','en','es','de') then
    raise exception 'invalid language';
  end if;

  insert into public.liio_families(owner_secret_hash, parent_name)
  values (public.liio_hash(p_owner_secret), trim(p_parent_name))
  returning id into v_family_id;

  insert into public.liio_preferences(family_id, language)
  values (v_family_id, p_language);

  return v_family_id;
end;
$$;

create or replace function public.liio_list_children_owner(
  p_family_id uuid,
  p_owner_secret text
)
returns table(id uuid, name text, age integer)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.liio_owner_matches(p_family_id, p_owner_secret) then
    raise exception 'unauthorized';
  end if;

  return query
  select c.id, c.name, c.age
  from public.liio_children c
  where c.family_id = p_family_id
  order by c.created_at;
end;
$$;

create or replace function public.liio_upsert_child(
  p_family_id uuid,
  p_owner_secret text,
  p_child_id uuid,
  p_name text,
  p_age integer
)
returns table(id uuid, name text, age integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  if not public.liio_owner_matches(p_family_id, p_owner_secret) then
    raise exception 'unauthorized';
  end if;

  if p_age < 6 or p_age > 15 then
    raise exception 'invalid age';
  end if;

  if p_child_id is null then
    insert into public.liio_children(family_id, name, age)
    values (p_family_id, trim(p_name), p_age)
    returning liio_children.id into v_id;

    insert into public.liio_time_limits(child_id)
    values (v_id)
    on conflict do nothing;
  else
    update public.liio_children
    set name = trim(p_name),
        age = p_age,
        updated_at = now()
    where liio_children.id = p_child_id
      and family_id = p_family_id
    returning liio_children.id into v_id;

    if v_id is null then
      raise exception 'child not found';
    end if;
  end if;

  return query
  select c.id, c.name, c.age
  from public.liio_children c
  where c.id = v_id;
end;
$$;

create or replace function public.liio_delete_child(
  p_family_id uuid,
  p_owner_secret text,
  p_child_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.liio_owner_matches(p_family_id, p_owner_secret) then
    raise exception 'unauthorized';
  end if;

  delete from public.liio_children
  where id = p_child_id
    and family_id = p_family_id;

  return found;
end;
$$;

create or replace function public.liio_random_code()
returns text
language plpgsql
volatile
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  bytes bytea := gen_random_bytes(6);
  result text := '';
  i integer;
begin
  for i in 0..5 loop
    result := result || substr(
      alphabet,
      (get_byte(bytes, i) % char_length(alphabet)) + 1,
      1
    );
  end loop;

  return result;
end;
$$;

create or replace function public.liio_create_pairing_code(
  p_family_id uuid,
  p_owner_secret text
)
returns table(code text, expires_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
  v_expires timestamptz := now() + interval '10 minutes';
begin
  if not public.liio_owner_matches(p_family_id, p_owner_secret) then
    raise exception 'unauthorized';
  end if;

  delete from public.liio_pairing_codes
  where expires_at < now()
     or redeemed_at is not null;

  loop
    v_code := public.liio_random_code();

    begin
      insert into public.liio_pairing_codes(
        family_id,
        code_hash,
        expires_at
      )
      values (
        p_family_id,
        public.liio_hash(v_code),
        v_expires
      );

      exit;
    exception when unique_violation then
      -- try a new code
    end;
  end loop;

  return query
  select
    substr(v_code, 1, 3) || '-' || substr(v_code, 4, 3),
    v_expires;
end;
$$;

create or replace function public.liio_pairing_children(
  p_code text
)
returns table(id uuid, name text, age integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_family_id uuid;
  v_normalized text := upper(regexp_replace(p_code, '[^A-Z0-9]', '', 'g'));
begin
  select pc.family_id
  into v_family_id
  from public.liio_pairing_codes pc
  where pc.code_hash = public.liio_hash(v_normalized)
    and pc.expires_at > now()
    and pc.redeemed_at is null
  limit 1;

  if v_family_id is null then
    raise exception 'invalid or expired code';
  end if;

  return query
  select c.id, c.name, c.age
  from public.liio_children c
  where c.family_id = v_family_id
  order by c.created_at;
end;
$$;

create or replace function public.liio_activate_device(
  p_code text,
  p_child_id uuid,
  p_device_token text
)
returns table(
  family_id uuid,
  child_id uuid,
  child_name text,
  child_age integer,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_family_id uuid;
  v_normalized text := upper(regexp_replace(p_code, '[^A-Z0-9]', '', 'g'));
  v_expires timestamptz := now() + interval '30 days';
begin
  if char_length(p_device_token) < 32 then
    raise exception 'invalid device token';
  end if;

  select pc.family_id
  into v_family_id
  from public.liio_pairing_codes pc
  where pc.code_hash = public.liio_hash(v_normalized)
    and pc.expires_at > now()
    and pc.redeemed_at is null
  for update
  limit 1;

  if v_family_id is null then
    raise exception 'invalid or expired code';
  end if;

  if not exists (
    select 1
    from public.liio_children c
    where c.id = p_child_id
      and c.family_id = v_family_id
  ) then
    raise exception 'child not in family';
  end if;

  update public.liio_pairing_codes
  set redeemed_at = now()
  where code_hash = public.liio_hash(v_normalized);

  insert into public.liio_device_sessions(
    family_id,
    child_id,
    token_hash,
    expires_at
  )
  values (
    v_family_id,
    p_child_id,
    public.liio_hash(p_device_token),
    v_expires
  );

  return query
  select
    v_family_id,
    c.id,
    c.name,
    c.age,
    v_expires
  from public.liio_children c
  where c.id = p_child_id;
end;
$$;

create or replace function public.liio_device_child(
  p_device_token text
)
returns table(
  child_id uuid,
  child_name text,
  child_age integer,
  family_id uuid
)
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.liio_device_sessions
  set last_seen_at = now()
  where token_hash = public.liio_hash(p_device_token)
    and expires_at > now();

  return query
  select c.id, c.name, c.age, ds.family_id
  from public.liio_device_sessions ds
  join public.liio_children c on c.id = ds.child_id
  where ds.token_hash = public.liio_hash(p_device_token)
    and ds.expires_at > now()
  limit 1;
end;
$$;

revoke all on public.liio_families from anon, authenticated;
revoke all on public.liio_children from anon, authenticated;
revoke all on public.liio_preferences from anon, authenticated;
revoke all on public.liio_pairing_codes from anon, authenticated;
revoke all on public.liio_device_sessions from anon, authenticated;
revoke all on public.liio_time_limits from anon, authenticated;
revoke all on public.liio_learning_sessions from anon, authenticated;
revoke all on public.liio_activity_events from anon, authenticated;

grant execute on function public.liio_create_family(text, text, text) to anon, authenticated;
grant execute on function public.liio_list_children_owner(uuid, text) to anon, authenticated;
grant execute on function public.liio_upsert_child(uuid, text, uuid, text, integer) to anon, authenticated;
grant execute on function public.liio_delete_child(uuid, text, uuid) to anon, authenticated;
grant execute on function public.liio_create_pairing_code(uuid, text) to anon, authenticated;
grant execute on function public.liio_pairing_children(text) to anon, authenticated;
grant execute on function public.liio_activate_device(text, uuid, text) to anon, authenticated;
grant execute on function public.liio_device_child(text) to anon, authenticated;
